/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car;

import java.awt.List;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    // make sure your path is correct --_--   <<<<------
    private final String File = "C:\\Users\\Ryan\\Documents\\NetBeansProjects\\Car\\src\\car\\Data.txt";
    
    HashSet<String> maker;
    Map<String, HashSet<String>> maker_model;
    Map<String, HashSet<String>> model_year;
    Map<String, HashSet<String>> year_engine;
    Map<String, String> result;
    
    
    
    public main() {
        initComponents();
        this.setTitle("Mechanic's Wife");
        this.setLocationRelativeTo(null);
        this.initialize();
    }
    
    public void initialize(){
        
        maker_model = new HashMap<>();
        model_year = new HashMap<>();
        year_engine = new HashMap<>();
        result = new HashMap<>();
        init_data();
        
       
    }
    
    public String getFile(){
        return this.File;
    }
    
    private void init_data(){
        BufferedReader br = null;
        try{
            br = new BufferedReader(new FileReader(File));
            String line, make, model, year, engine, res = "";
            while((line = br.readLine())!= null && line.length() != 0){
                int left = 0;
                res = "";
                String[] temp = line.split(" ");
                make = temp[0];
                model = temp[1];
                engine = temp[2];
                year = temp[3];
                for(int i = 4; i < temp.length; i++){
                    res += (temp[i] + " ");
                }
                if(!maker_model.containsKey(make)) maker_model.put(make, new HashSet<>());
                maker_model.get(make).add(model);
                if(!model_year.containsKey(model)) model_year.put(model, new HashSet<>());
                model_year.get(model).add(year);
                if(!year_engine.containsKey(year)) year_engine.put(year, new HashSet<>());
                year_engine.get(year).add(engine);
               
                result.put(make + model + year + engine, res);
                
                
            }
            
            br.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"File Input Error","Crush",JOptionPane.WARNING_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Maker = new javax.swing.JTextField();
        okay = new javax.swing.JButton();
        Model = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextArea();
        Engine = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Make");

        jLabel3.setText("Model");

        jLabel4.setText("Year");

        jLabel5.setText("Engine");

        Maker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakerActionPerformed(evt);
            }
        });

        okay.setText("Let's Go Go Go");
        okay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                okayFocusGained(evt);
            }
        });
        okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayActionPerformed(evt);
            }
        });

        Model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelActionPerformed(evt);
            }
        });

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        jLabel6.setText("Result");

        Result.setColumns(20);
        Result.setRows(5);
        jScrollPane1.setViewportView(Result);

        Engine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        Engine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineActionPerformed(evt);
            }
        });

        update.setText("Update Data");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Maker)
                            .addComponent(Model, 0, 88, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(okay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Engine, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Maker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okay)
                    .addComponent(update))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Engine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayActionPerformed
        // set model combobox
        String make = "";
        Model.removeAllItems();
        try{
            if(!Maker.getText().isEmpty()){
                make = Maker.getText().toUpperCase();
            }
            for(String s : maker_model.get(make)){        
                Model.addItem(s);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Sorry, Can't find this car!","OOps",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_okayActionPerformed
    
    private void ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelActionPerformed
        //set year combobox
        Year.removeAllItems();
        try{
              
            String model = (String) Model.getSelectedItem();
               
            if(model_year.get(model) != null){
                for(String i : model_year.get(model)){
                    Year.addItem(i + "");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Input Error Model","Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_ModelActionPerformed

    private void MakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakerActionPerformed
        
    }//GEN-LAST:event_MakerActionPerformed

    private void EngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineActionPerformed
        Result.setText("");
        try{
            if( Engine.getSelectedItem() != null){
                String engine  = (String) Engine.getSelectedItem();
                String model = (String) Model.getSelectedItem();
                String year = (String) Year.getSelectedItem();
                String make = (String) Maker.getText().toUpperCase();
                String res = result.get(make + model + year + engine);
                Result.setText(res);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Input Error Engine","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EngineActionPerformed
    
    
    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // set engine
        Engine.removeAllItems();
        try{
            String year  =  (String) Year.getSelectedItem();
           
            
            //System.out.println(kkey);
            if(year_engine.get(year) != null){
                for(String s : year_engine.get(year)){
                    Engine.addItem(s);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Input Error Year","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_YearActionPerformed

    private void okayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_okayFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_okayFocusGained

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         Log_In ob = new Log_In(this, true);
        
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Engine;
    private javax.swing.JTextField Maker;
    private javax.swing.JComboBox<String> Model;
    private javax.swing.JTextArea Result;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okay;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
